[package]
name = "tpg"
version = "0.0.5"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
colored = "2.1.0"
pgp = "0.14.0"
rand = "0.8.5"
smallvec = "1.13.2"
